author = 'Oxalin'
country_code = 'GB'
description = "The south section of the West Coast Main Line, from London Euston to Watford Junction"
display_name = 'WCML Euston to Watford Junction'
doc_files = [ 'WCML Euston to Watford Junction.md' ]
factual = true
img_files = [ 'WCML Euston to Watford Junction.bmp' ]
name = 'WCML Euston to Watford Junction'
release_date = '2023-05-07'
rly_file = 'WCML Euston to Watford Junction.rly'
ssn_files = [ 'WCML Euston to Watford Junction Initial Session.ssn']
ttb_files = [ 'WCML Euston to Watford Junction 07-05-23.ttb' ]
version = '1.0.0'
